import type { Metadata } from 'next';
import localFont from 'next/font/local';

import './globals.css';

const Satoshi = localFont({ src: '../../font/Satoshi-Variable.woff2' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${Satoshi.className} antialiased`}>{children}</body>
    </html>
  );
}
